services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: tmapi_root
      POSTGRES_PASSWORD: 546258
      POSTGRES_DB: tmapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - postgres-network

volumes:
  postgres_data:

networks:
  postgres-network:
    driver: bridge
